upd node extra template

diff --git a/templates/node-extras/Dockerfile b/templates/node-extras/Dockerfile
--- a/templates/node-extras/Dockerfile
+++ b/templates/node-extras/Dockerfile
@@ -11,28 +11,27 @@ RUN apk --update add make python gcc g++
 RUN npm install -g nodemon
 RUN npm install -g pm2
 
-RUN echo 'set -e' > /usr/bin/start.sh # this is the script which will run on start
+RUN echo 'set -e' > /boot.sh # this is the script which will run on start
 
 # Basic npm start verification
-RUN echo 'nb=`cat package.json | grep start | wc -l` && if test "$nb" = "0" ; then echo "*** Boot issue: No start command found in your package.json in the scripts. See https://docs.npmjs.com/cli/start" ; exit 1 ; fi' >> /usr/bin/start.sh
-
-# if you need a build script, uncomment the line below
-# RUN echo 'sh mybuild.sh' >> /usr/bin/start.sh
+RUN echo 'nb=`cat package.json | grep start | wc -l` && if test "$nb" = "0" ; then echo "*** Boot issue: No start command found in your package.json in the scripts. See https://docs.npmjs.com/cli/start" ; exit 1 ; fi' >> /boot.sh
 
 # if you need redis, uncomment the lines below
 # RUN apk --update add redis
-# RUN echo 'redis-server &' >> /usr/bin/start.sh
+# RUN echo 'redis-server &' >> /boot.sh
 
 # daemon for cron jobs
-RUN echo 'echo will install crond...' >> /usr/bin/start.sh
-RUN echo 'crond' >> /usr/bin/start.sh
+RUN echo 'echo will install crond...' >> /boot.sh
+RUN echo 'crond' >> /boot.sh
 
 # install packages
-RUN echo 'npm install --production' >> /usr/bin/start.sh
+RUN echo 'npm install --production' >> /boot.sh
 
 # logs by default are in logs
 RUN mkdir -p logs
 
 # npm start, make sure to have a start attribute in "scripts" in package.json
-RUN echo 'pm2 --output logs/out.log --error logs/error.log start npm -- start' >> /usr/bin/start.sh
-RUN echo 'sh' >> /usr/bin/start.sh
+RUN echo 'pm2 --output logs/out.log --error logs/error.log start npm -- start' >> /boot.sh
+RUN echo 'sh' >> /boot.sh
+
+CMD sh /boot.sh
